import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import Wallet from './components/Wallet';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>my-wallet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className='text-center mt-4 mb-3'>My-Wallet</h1>
      <Wallet />
    </div>
  )
}
