import Head from 'next/head'
import styles from '../styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.min.css';
// import Wallet from './components/Wallet';
import InputForm from './components/InputForm';
// import History from './components/History';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>my-wallet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className='text-center pt-3 pb-3 mb-3 bg-info text-white'>My-Wallet</h1>
      <InputForm />
    </div>
  )
}
